<?php

namespace MainBundle\Repository;

/**
 * CalificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
