<?php

namespace MainBundle\Repository;

/**
 * CalificacionHuespedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionHuespedRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecibidasAsGuest($userId){
        $dql='SELECT c, c.puntaje, c.comentario, u.nombre as nombre, u.apellido as apellido, h.titulo as hosp
              FROM MainBundle:CalificacionHuesped c
              INNER JOIN MainBundle:Usuario u WITH u.id = c.usercalificador
              INNER JOIN MainBundle:Hospedaje h WITH h.usuario = c.usercalificador
              WHERE c.usercalificado = :userId';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':userId', $userId)
            ->getResult();
    }

    public function findRecibidasAsOwner($userId){
        $dql='SELECT c, c.puntaje, c.comentario, u.nombre as nombre, u.apellido as apellido, h.titulo as hosp
              FROM MainBundle:Calificacion c
              INNER JOIN MainBundle:Usuario u WITH u.id = c.usuario
              INNER JOIN MainBundle:Hospedaje h WITH h.id = c.hospedaje
              WHERE h.usuario = :userId';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':userId', $userId)
            ->getResult();
    }

    public function findOtorgadasToGuest($userId){
        $dql='SELECT c, c.puntaje, c.comentario, u.nombre as nombre, u.apellido as apellido, h.titulo as hosp
              FROM MainBundle:CalificacionHuesped c
              INNER JOIN MainBundle:Usuario u WITH u.id = c.usercalificado
              INNER JOIN MainBundle:Hospedaje h WITH h.usuario = c.usercalificado
              WHERE c.usercalificador = :userId';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':userId', $userId)
            ->getResult();
    }

    public function findOtorgadasToHosp($userId){
        $dql='SELECT c, c.puntaje, c.comentario, h.titulo as hosp
              FROM MainBundle:CalificacionHuesped c
              INNER JOIN MainBundle:Hospedaje h WITH h.usuario = c.usercalificador
              WHERE c.usercalificador = :userId';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':userId', $userId)
            ->getResult();
    }
}
