<?php

namespace MainBundle\Repository;

/**
 * ConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaRepository extends \Doctrine\ORM\EntityRepository
{
}
