<?php

namespace MainBundle\Repository;

/**
 * FavoritosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritosRepository extends \Doctrine\ORM\EntityRepository
{
}
