<?php

namespace MainBundle\Repository;

/**
 * PreguntaSeguridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaSeguridadRepository extends \Doctrine\ORM\EntityRepository
{
}
