<?php

namespace MainBundle\Repository;

/**
 * ReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDisponibilidad($from, $to){
        $dql = 'SELECT h, h.borrado, h.titulo, h.id, h.direccion, h.localidad, h.descripcion, h.capacidad, h.precio, th.nombre as tipoHosp
                FROM MainBundle:Hospedaje h 
                INNER JOIN MainBundle:TipoHospedaje th WITH h.tipohospedaje = th.id
                WHERE h.id NOT IN (
                SELECT IDENTITY (r.hospedaje) FROM MainBundle:Reserva r 
                WHERE ((r.fechaInicio <= :desde AND r.fechaFin >= :desde) OR 
                      ( r.fechaInicio <= :hasta AND r.fechaFin >= :hasta) OR 
                      ( r.fechaInicio > :desde AND r.fechaFin < :hasta))
                )';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters(['desde'=>$from, 'hasta'=>$to])
            ->getResult();
    }

    public function findOneByReserva($idHospedaje){
        $dql = 'SELECT r FROM MainBundle:Reserva r WHERE r.hospedaje = :idHospedaje';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':idHospedaje', $idHospedaje)
            ->getResult();
    }


    public function findMisReservas($userId){
        $dql = 'SELECT r, r.id, r.fechaInicio, r.fechaFin, IDENTITY (r.hospedaje), r.monto, r.confirmada, h.titulo as titulo, 
                h.id as hospId, h.borrado as borrado 
                FROM MainBundle:Reserva r 
                INNER JOIN MainBundle:Hospedaje h WITH r.hospedaje = h.id
                WHERE (r.usuario = :userId AND r.confirmada = 0)';
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':userId', $userId)
            ->getResult();
    }

}
