<?php

namespace MainBundle\Repository\Entity;

/**
 * HospedajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospedajeRepository extends \Doctrine\ORM\EntityRepository
{
}
