<?php

namespace MainBundle\Repository\Entity;

/**
 * TipoHospedajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoHospedajeRepository extends \Doctrine\ORM\EntityRepository
{
}
